<?php

namespace app\controllers;

use app\components\message\Language;
use app\models\About;
use app\models\Banner;
use app\models\Category;
use app\models\Contact;
use app\models\Culture;
use app\models\Partner;
use app\models\Process;
use app\models\Product;
use app\models\Service;
use Yii;
use app\models\News;
use yii\web\Controller;
use yii\filters\VerbFilter;

class SiteController extends Controller
{
    public $layout = 'main';
    public function behaviors()
    {
      return [
          'verbs' => [
              'class' => VerbFilter::className(),
              'actions' => [
                  'delete' => ['POST'],
                  'logout' => ['POST'],
              ],
          ],
      ];
    }
    public function beforeAction($action)
    {
        $config = Yii::$app->cache->get('config_'.\app\components\message\Language::getLanguageNum());
        if(empty($config))
        {
            $config = getWebConfig();
            Yii::$app->cache->set('config_'.\app\components\message\Language::getLanguageNum(), $config);
        }
        $this->view->params['config'] = $config;
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }
    public function afterAction($action, $result)
    {
        return parent::afterAction($action, $result); // TODO: Change the autogenerated stub
    }

    //首页
    public function actionIndex()
    {
        $config = Yii::$app->cache->get('config_'.\app\components\message\Language::getLanguageNum());
        $banner = \app\models\Banner::getBanner('home');

        $product = Partner::getIndexList(4);

        $serviceCate = Category::getCategoryList('service');

        $about = About::findOne(Language::getLanguageNum());

        $news = Culture::getIndexList(2);

        return $this->render('index', [
            'config' => $config,
            'banner' => $banner,
            'product' => $product,
            'serviceCate' => $serviceCate,
            'about' => $about,
            'news' => $news,
        ]);
    }

    /**
     * 关于我们
     * @return string
     */
    public function actionAbout()
    {
        $id = Yii::$app->request->get('id', 0);
        $banner = \app\models\Banner::getBanner('about');

        $model = About::getDetail($id);
        $category = About::getCategory();
        return $this->render('about',[
            'model' => $model,
            'category' => $category,
            'banner' => $banner,
        ]);
    }

    /**
     * 钜新服务
     * @return string
     */
    public function actionService()
    {
        $id = Yii::$app->request->get('id', 0);
        $banner = \app\models\Banner::getBanner('service');

        $model = Service::getDetail($id);
        $category = Service::getCategory();
        return $this->render('service',[
            'model' => $model,
            'category' => $category,
            'banner' => $banner,
        ]);
    }

    /**
     * 合作流程
     * @return string
     */
    public function actionProcess()
    {
        $id = Yii::$app->request->get('id', 0);
        $banner = \app\models\Banner::getBanner('process');

        $model = Process::getDetail($id);
        $category = Process::getCategory();
        return $this->render('process',[
            'model' => $model,
            'category' => $category,
            'banner' => $banner,
        ]);
    }


    /**
     * 联系我们
     * @return string
     */
    public function actionContact()
    {
        $id = Yii::$app->request->get('id', 0);
        $banner = \app\models\Banner::getBanner('contact');

        $model = Contact::getDetail($id);
        $category = Contact::getCategory();
        return $this->render('contact',[
            'model' => $model,
            'category' => $category,
            'banner' => $banner,
        ]);
    }
    /**
     * 文化传播列表
     * @return string
     */
    public function actionCulture()
    {
        $md = 'culture';
        $banner = \app\models\Banner::getBanner($md);
        $category = Category::getCategoryList($md);
        $model = new Culture();
        $ret = $model::getList();
        if($ret['success'])
        {
            $list = $ret['list'];
            $pages = $ret['pages'];
            return $this->render('cultureList',[
                'model' => $model,
                'list' => $list,
                'pages' => $pages,
                'banner' => $banner,
                'category' => $category,
            ]);
        }
        else
        {
            return $this->render('cultureList',[
                'list' => [],
                'banner' => $banner,
                'category' => $category,
            ]);
        }

    }

    /**
     * 文化传播详情
     * @param $id
     * @return string|\yii\web\Response
     */
    public function actionCultureDetail($id)
    {
        $md = 'culture';
        $banner = \app\models\Banner::getBanner($md);
        $category = Category::getCategoryList($md);
        $model = Culture::getDetail($id);
        if (empty($model)) {
            return $this->redirect(['culture']);
        } else {
            return $this->render('cultureDetail', [
                'model' => $model,
                'banner' => $banner,
                'category' => $category,
            ]);
        }
    }

    /**
     * 案例列表
     * @return string
     */
    public function actionCases()
    {
        $md = 'cases';
        $banner = \app\models\Banner::getBanner($md);
        $category = Category::getCategoryList($md);
        $model = new Partner();
        $ret = $model::getList();
        if($ret['success'])
        {
            $list = $ret['list'];
            $pages = $ret['pages'];
            return $this->render('casesList',[
                'model' => $model,
                'list' => $list,
                'pages' => $pages,
                'banner' => $banner,
                'category' => $category,
            ]);
        }
        else
        {
            return $this->render('casesList',[
                'list' => [],
                'banner' => $banner,
                'category' => $category,
            ]);
        }

    }

    /**
     * 案例详情
     * @param $id
     * @return string|\yii\web\Response
     */
    public function actionCasesDetail($id)
    {
        $md = 'cases';
        $banner = \app\models\Banner::getBanner($md);
        $category = Category::getCategoryList($md);
        $model = Partner::getDetail($id);
        if (empty($model)) {
            return $this->redirect(['cases']);
        } else {
            return $this->render('casesDetail', [
                'model' => $model,
                'banner' => $banner,
                'category' => $category,
            ]);
        }
    }


    //------------------------------------------------------------------------//

    //错误显示页
    public function actions()
    {
      return [
        'error' => [
          'class' => 'yii\web\ErrorAction',
        ],
      ];
    }


}
